name: signature_system
description: "A new Flutter project."
version: 1.0.7+1

environment:
  sdk: ^3.5.0
dependencies:
  intl:
  web:
  syncfusion_flutter_pdf:
  image:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dropdown_search: ^6.0.2
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.0.0+2
  device_info_plus: ^11.3.0
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  intl_phone_field: ^3.2.0
  path_provider: ^2.1.5
  # Firebase
  firebase_core:
  firebase_auth_web:
  firebase_auth:
  cloud_firestore:
  fluttertoast:
  # Linking
  url_launcher:
  # State Management
  get_it:
  flutter_bloc:
  # Asset management
  flutter_cache_manager: ^3.4.1
  flutter_svg:
  flutter_pdfview: ^1.4.0
  html: ^0.15.5
  syncfusion_flutter_pdfviewer: ^28.2.5
  file_picker: ^8.3.1
  universal_html:
  pdf: ^3.11.2
  firebase_storage: ^12.4.4
  http:
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/background.png